ru:
  ilyshka_fox:
    controller:
      api-key: 82b2989c-0cab-4c2e-aec6-d2443da4f5f7
    service:
      rucaptcha:
        api-key: 9b65c6f3637309baff75b0d5758d0b0b
      web-client:
        max-in-memory-size: 16777216
      vk:
        login: ilya_moslov@mail.ru
        password: