GET https://static.checkback.vkforms.ru/api/v1/scan?page=1&limit=100
Accept: application/json
X-vk-sign: ?vk_access_token_settings=friends&vk_app_id=7550574&vk_are_notifications_enabled=1&vk_is_app_user=1&vk_is_favorite=0&vk_language=ru&vk_platform=mobile_web&vk_ref=catalog_recent&vk_ts=1649582566&vk_user_id=146327166&sign=x48kw_NgJyA6Oijj9-9m5onWiGHWQ_qpBeS4RwlK9kA
